name = "twitch-roll"
main = "src/index.js"
compatibility_date = "2023-04-17"
vars = {BASE_URL = "http://localhost:8787"}

kv_namespaces = [
  { binding = "TWITCH_TOKEN_SPACE", id = "_SOME_ID_", preview_id = "_SOME_ID_" }
]
[env.dev]
vars = {BASE_URL = "http://localhost:8787"}
kv_namespaces = [
  { binding = "TWITCH_TOKEN_SPACE", id = "_SOME_ID_", preview_id = "_SOME_ID_" }
]

[env.production]
vars = {BASE_URL = "https://example.com"}
kv_namespaces = [
  { binding = "TWITCH_TOKEN_SPACE", id = "_SOME_ID_", preview_id = "_SOME_ID_" }
]